
export const LOGIN='LOGIN'
export const SHOW_CATEGORIES='SHOW_CATEGORIES'
export const SHOWFOOD='SHOWFOOD'
export const SHOWTECHNOLOGY='SHOWTECHNOLOGY'
export const SHOWCARS='SHOWCARS'
export const SHOWSPORT='SHOWSPORT'
export const SHOWMAKEUP = 'SHOWMAKEUP'
export const SHOWCLOTHES='SHOWCLOTHES'
export const SHOW_COMMENTS="SHOW_COMMENTS"
export const SELECT_ITEM='SELECT_ITEM'
export const SEARCH = 'SEARCH'
export const DELETE_CART='DELETE_CART'
export const ADD_TO_CART='ADD_TO_CART'